apiVersion: batch/v1beta1
kind: CronJob


metadata:
  name: batch-job-every-fifiteen-minutes


spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodc-batch-job
        spec:
          containers:
            - name: main
              image: luksa/batch-job

          restartPolicy: OnFailure
  schedule: "0,15,30,45 * * * *"



